export const WORLDBOOK_CONTENT_BEGIN = '@@CHUNXIN_WORLDBOOK_CONTENT_BEGIN@@';
export const WORLDBOOK_CONTENT_END = '@@CHUNXIN_WORLDBOOK_CONTENT_END@@';

export const STORY_DIRECTOR_BEGIN = '@@CHUNXIN_STORY_DIRECTOR_BEGIN@@';
export const STORY_DIRECTOR_END = '@@CHUNXIN_STORY_DIRECTOR_END@@';
