import type { AppSubViewRenderParams } from './types';

export const buildContentSubViewRenderParams = (options: AppSubViewRenderParams): AppSubViewRenderParams => ({
  goBackSubView: options.goBackSubView,
  pushSubView: options.pushSubView,
  contacts: options.contacts,
  worldBooks: options.worldBooks,
  htmlTemplates: options.htmlTemplates,
  bubbleTemplates: options.bubbleTemplates,
  setContacts: options.setContacts,
  setWorldBooks: options.setWorldBooks,
  setHtmlTemplates: options.setHtmlTemplates,
  setBubbleTemplates: options.setBubbleTemplates,
  setMessages: options.setMessages,
  activeCommunityShareId: options.activeCommunityShareId,
  setActiveCommunityShareId: options.setActiveCommunityShareId,
  showToast: options.showToast,
  replaceSubView: options.replaceSubView,
  masks: options.masks,
  user: options.user,
  forums: options.forums,
  setForums: options.setForums,
  aiSettings: options.aiSettings,
  runtimeUserPromptBase: options.runtimeUserPromptBase,
  officialArticles: options.officialArticles,
  setOfficialArticles: options.setOfficialArticles,
  musicState: options.musicState,
  handleMusicStateChange: options.handleMusicStateChange,
  handleOpenOfficialArticle: options.handleOpenOfficialArticle,
  handleManualGenerateOfficialArticle: options.handleManualGenerateOfficialArticle,
  handleGenerateInitialArticleComments: options.handleGenerateInitialArticleComments,
  handleGenerateReplyToArticleComment: options.handleGenerateReplyToArticleComment,
  handleOfficialArticleCommentsChange: options.handleOfficialArticleCommentsChange,
  handleDeleteCurrentOfficialArticle: options.handleDeleteCurrentOfficialArticle,
  handleRemindWhoPost: options.handleRemindWhoPost,
  handleContactPickerConfirm: options.handleContactPickerConfirm,
  handleStickerImportConfirm: options.handleStickerImportConfirm
});
