import { useMemo } from 'react';
import { buildSubViewRenderParams } from '../app/buildSubViewRenderParams';
import { ANONYMOUS_CHAT_ID } from '../app/anonymousChatUtils';
import type { UseSubViewRenderBridgeParams } from './subViewRenderBridgeTypes';

export const useSubViewRenderParams = (params: UseSubViewRenderBridgeParams) => {
  const {
    state: s,
    currentChat,
    currentProfile,
    ifLineContacts,
    getProfilePlaceholder,
    handleHighContextLimitWarning,
    runtimeUserPromptBase,
    buildRuntimePromptWithMemory,
    setIsChatInputFocused,
    contactHandlers,
    actionHandlers
  } = params;

  return useMemo(() => buildSubViewRenderParams({
    currentChat,
    selectedContactId: s.selectedContactId,
    user: s.user,
    contacts: s.contacts,
    ifLineContacts,
    messages: s.messages,
    settings: s.settings,
    soundVibrationSettings: s.soundVibrationSettings,
    inputValue: s.inputValue,
    setInputValue: s.setInputValue,
    inputMode: s.inputMode,
    setInputMode: s.setInputMode,
    showPanel: s.showPanel,
    setShowPanel: s.setShowPanel,
    typingContactIds: s.typingContactIds,
    aiSettings: s.aiSettings,
    quotedMessage: s.quotedMessage,
    setQuotedMessage: s.setQuotedMessage,
    activePaymentMessage: s.activePaymentMessage,
    setActivePaymentMessage: s.setActivePaymentMessage,
    showRedPacketPreview: s.showRedPacketPreview,
    setShowRedPacketPreview: s.setShowRedPacketPreview,
    handleSendMessage: actionHandlers.handleSendMessage,
    handleGenerateChatReplies: actionHandlers.handleGenerateChatReplies,
    handleChatTempSend: actionHandlers.handleChatTempSend,
    handleChatBack: actionHandlers.handleChatBack,
    handleChatMore: actionHandlers.handleChatMore,
    handleChatVoiceCallStateChange: actionHandlers.handleChatVoiceCallStateChange,
    resolvedRenderConfig: s.resolvedRenderConfig,
    handleChatAvatarClick: actionHandlers.handleChatAvatarClick,
    pushSubView: s.pushSubView,
    handleMessageAction: actionHandlers.handleMessageAction,
    handleChatPaymentClick: actionHandlers.handleChatPaymentClick,
    handleChatAppendMessage: actionHandlers.handleChatAppendMessage,
    handleChatPat: actionHandlers.handleChatPat,
    onIfLineSelect: contactHandlers.handleIfLineSelect,
    onIfLineAction: contactHandlers.handleIfLineAction,
    handleConfirmReceiveTransfer: actionHandlers.handleConfirmReceiveTransfer,
    handleConfirmReceiveRedPacket: actionHandlers.handleConfirmReceiveRedPacket,
    goBackSubView: s.goBackSubView,
    ANONYMOUS_CHAT_ID,
    anonymousViewingHistoryId: s.anonymousViewingHistoryId,
    anonymousPartner: s.anonymousPartner,
    anonymousSessionActive: s.anonymousSessionActive,
    anonymousIsMatching: s.anonymousIsMatching,
    anonymousHasUnfinishedSession: s.anonymousHasUnfinishedSession,
    anonymousUnfinishedSession: s.anonymousUnfinishedSession,
    anonymousSettingsVisible: s.anonymousSettingsVisible,
    anonymousChatSettings: s.anonymousChatSettings,
    anonymousTagDraft: s.anonymousTagDraft,
    setAnonymousTagDraft: s.setAnonymousTagDraft,
    setAnonymousChatSettings: s.setAnonymousChatSettings,
    setAnonymousSettingsVisible: s.setAnonymousSettingsVisible,
    rootSkinId: s.rootSkinId,
    handleStartAnonymousMatch: actionHandlers.handleStartAnonymousMatch,
    handleResumeAnonymousSession: actionHandlers.handleResumeAnonymousSession,
    handleAnonymousSend: actionHandlers.handleAnonymousSend,
    handleAnonymousLeave: actionHandlers.handleAnonymousLeave,
    anonymousInputValue: s.anonymousInputValue,
    setAnonymousInputValue: s.setAnonymousInputValue,
    masks: s.masks,
    worldBooks: s.worldBooks,
    handleHighContextLimitWarning,
    handleUpdateCurrentChat: actionHandlers.handleUpdateCurrentChat,
    handleUpdateCurrentChatGroupRelations: actionHandlers.handleUpdateCurrentChatGroupRelations,
    handleOpenGroupMemberProfile: actionHandlers.handleOpenGroupMemberProfile,
    handleOpenCurrentChatProfile: actionHandlers.handleOpenCurrentChatProfile,
    handleConfirmClearCurrentChatMessages: actionHandlers.handleConfirmClearCurrentChatMessages,
    handleConfirmDeleteCurrentContact: contactHandlers.handleConfirmDeleteCurrentContact,
    handleConfirmExitCurrentGroup: contactHandlers.handleConfirmExitCurrentGroup,
    setUser: s.setUser,
    moments: s.moments,
    profileId: s.profileId,
    handleMomentsAvatarClick: actionHandlers.handleMomentsAvatarClick,
    handleManualGenerateMoment: actionHandlers.handleManualGenerateMoment,
    setMoments: s.setMoments,
    handleMomentCommentCreate: actionHandlers.handleMomentCommentCreate,
    handlePublishMoment: actionHandlers.handlePublishMoment,
    handleRemindWhoPost: actionHandlers.handleRemindWhoPost,
    anonymousHistory: s.anonymousHistory,
    divinationDraft: s.divinationDraft,
    setDivinationDraft: s.setDivinationDraft,
    divinationHistory: s.divinationHistory,
    currentDivinationRecord: s.currentDivinationRecord,
    divinationSubmitting: s.divinationSubmitting,
    handleSubmitDivination: actionHandlers.handleSubmitDivination,
    handleOpenDivinationHistory: actionHandlers.handleOpenDivinationHistory,
    handleSelectDivinationHistory: actionHandlers.handleSelectDivinationHistory,
    handleSearchSelectContact: actionHandlers.handleSearchSelectContact,
    handleSelectAnonymousHistory: actionHandlers.handleSelectAnonymousHistory,
    currentProfile,
    profileSnapshot: s.profileSnapshot,
    getProfilePlaceholder,
    editingProfileField: s.editingProfileField,
    contactMemories: s.contactMemories,
    handleDeleteContact: contactHandlers.handleDeleteContact,
    handleOpenProfileChat: actionHandlers.handleOpenProfileChat,
    handleSetProfileRemark: actionHandlers.handleSetProfileRemark,
    handleOpenProfileMoments: actionHandlers.handleOpenProfileMoments,
    handleContactPersonaUpdate: actionHandlers.handleContactPersonaUpdate,
    handleContactMemoriesChange: actionHandlers.handleContactMemoriesChange,
    handleNavigateEditProfileField: actionHandlers.handleNavigateEditProfileField,
    setAiSettings: s.setAiSettings,
    setSettings: s.setSettings,
    setSoundVibrationSettings: s.setSoundVibrationSettings,
    setWorldBooks: s.setWorldBooks,
    editingWorldBook: s.editingWorldBook,
    handleEditWorldBook: actionHandlers.handleEditWorldBook,
    handleSaveWorldBook: actionHandlers.handleSaveWorldBook,
    setMasks: s.setMasks,
    editingMaskId: s.editingMaskId,
    handleEditMask: actionHandlers.handleEditMask,
    handleSaveMask: actionHandlers.handleSaveMask,
    handleSetContactChatBg: actionHandlers.handleSetContactChatBg,
    htmlTemplates: s.htmlTemplates,
    setHtmlTemplates: s.setHtmlTemplates,
    editingHtmlTemplateId: s.editingHtmlTemplateId,
    handleEditHtmlTemplate: (id: string) => {
      s.setEditingHtmlTemplateId(id);
      s.pushSubView('htmlTemplateEdit');
    },
    handleSaveHtmlTemplate: (next: any) => {
      s.setHtmlTemplates((prev: any[]) => prev.map((item: any) => item.id === next.id ? next : item));
    },
    bubbleTemplates: s.bubbleTemplates,
    setBubbleTemplates: s.setBubbleTemplates,
    editingBubbleTemplateId: s.editingBubbleTemplateId,
    handleEditBubbleTemplate: (id: string) => {
      s.setEditingBubbleTemplateId(id);
      s.pushSubView('bubbleTemplateEdit');
    },
    handleSaveBubbleTemplate: (next: any) => {
      s.setBubbleTemplates((prev: any[]) => prev.map((item: any) => item.id === next.id ? next : item));
    },
    buildSnapshot: actionHandlers.buildSnapshot,
    estimateTokens: actionHandlers.estimateTokens,
    handleBackup: actionHandlers.handleBackup,
    handleRestore: actionHandlers.handleRestore,
    handleClearStorage: actionHandlers.handleClearStorage,
    handleClearMailboxData: actionHandlers.handleClearMailboxData,
    handleClearForumData: actionHandlers.handleClearForumData,
    handleClearMusicData: actionHandlers.handleClearMusicData,
    handleClearAnonymousData: actionHandlers.handleClearAnonymousData,
    addFriendDraft: s.addFriendDraft,
    setAddFriendDraft: s.setAddFriendDraft,
    addFriendGreetingDraft: s.addFriendGreetingDraft,
    setAddFriendGreetingDraft: s.setAddFriendGreetingDraft,
    friendRequests: s.friendRequests,
    contactCardPreview: s.contactCardPreview,
    contactCardImage: s.contactCardImage,
    resetAddFriendDraft: actionHandlers.resetAddFriendDraft,
    handleAIGenerateContactForm: actionHandlers.handleAIGenerateContactForm,
    handleCreateFriendContact: actionHandlers.handleCreateFriendContact,
    handleFriendRequestIncoming: actionHandlers.handleFriendRequestIncoming,
    handleExportContactQr: actionHandlers.handleExportContactQr,
    handleAcceptFriendRequest: actionHandlers.handleAcceptFriendRequest,
    showToast: s.showToast,
    handleOpenGroupChat: actionHandlers.handleOpenGroupChat,
    handleCreateGroupConfirm: actionHandlers.handleCreateGroupConfirm,
    parseContactFromCardImage: actionHandlers.parseContactFromCardImage,
    handleScanRequestCreated: actionHandlers.handleScanRequestCreated,
    handleShakeCreateContact: actionHandlers.handleShakeCreateContact,
    handleSendRedPacket: actionHandlers.handleSendRedPacket,
    handleSendTransfer: actionHandlers.handleSendTransfer,
    handleSendLocation: actionHandlers.handleSendLocation,
    walletBalance: s.walletBalance,
    walletBank: s.walletBank,
    handleEditWalletBank: actionHandlers.handleEditWalletBank,
    handleWalletTopUpConfirm: actionHandlers.handleWalletTopUpConfirm,
    handleWalletWithdrawConfirm: actionHandlers.handleWalletWithdrawConfirm,
    favorites: s.favorites,
    mailboxTheme: s.mailboxTheme,
    setMailboxTheme: s.setMailboxTheme,
    inboxLetters: s.inboxLetters,
    sentLetters: s.sentLetters,
    selectedMailboxType: s.selectedMailboxType,
    selectedMailboxLetter: s.selectedMailboxLetter,
    handleSelectMailboxLetter: actionHandlers.handleSelectMailboxLetter,
    handleSendMailboxLetter: actionHandlers.handleSendMailboxLetter,
    setContacts: s.setContacts,
    setMessages: s.setMessages,
    activeCommunityShareId: s.activeCommunityShareId,
    setActiveCommunityShareId: s.setActiveCommunityShareId,
    officialArticles: s.officialArticles,
    setOfficialArticles: s.setOfficialArticles,
    replaceSubView: s.replaceSubView,
    musicState: s.musicState,
    handleMusicStateChange: s.handleMusicStateChange,
    handleOpenOfficialArticle: actionHandlers.handleOpenOfficialArticle,
    handleManualGenerateOfficialArticle: actionHandlers.handleManualGenerateOfficialArticle,
    handleGenerateInitialArticleComments: actionHandlers.handleGenerateInitialArticleComments,
    handleGenerateReplyToArticleComment: actionHandlers.handleGenerateReplyToArticleComment,
    handleOfficialArticleCommentsChange: actionHandlers.handleOfficialArticleCommentsChange,
    handleDeleteCurrentOfficialArticle: actionHandlers.handleDeleteCurrentOfficialArticle,
    handleContactPickerConfirm: actionHandlers.handleContactPickerConfirm,
    handleStickerImportConfirm: actionHandlers.handleStickerImportConfirm,
    forums: s.forums,
    setForums: s.setForums,
    runtimeUserPromptBase,
    buildRuntimePromptWithMemory,
    onChatInputFocusChange: setIsChatInputFocused
  }), [
    actionHandlers,
    contactHandlers,
    currentChat,
    currentProfile,
    getProfilePlaceholder,
    handleHighContextLimitWarning,
    ifLineContacts,
    runtimeUserPromptBase,
    buildRuntimePromptWithMemory,
    s,
    setIsChatInputFocused
  ]);
};
