import { AppearanceSettings } from '../types';
import { type AppRenderConfig } from '../render-schema';

export const COLOR_KEYS: Array<{ key: keyof AppRenderConfig['colors']; label: string }> = [
  { key: 'accent', label: '主题色' },
  { key: 'bgPrimary', label: '主背景' },
  { key: 'bgSecondary', label: '次背景' },
  { key: 'bgTertiary', label: '三级背景' },
  { key: 'textPrimary', label: '主文字' },
  { key: 'textSecondary', label: '次文字' },
  { key: 'border', label: '边框' },
  { key: 'bubbleMe', label: '我方气泡' },
  { key: 'bubbleOther', label: '对方气泡' },
  { key: 'bubbleTextMe', label: '我方文字' },
  { key: 'bubbleTextOther', label: '对方文字' }
];

export const THEME_COLOR_PRESETS = [
  { name: '微信绿', accent: '#07c160', bubbleMe: '#95ec69', bubbleTextMe: '#111111' },
  { name: '天空蓝', accent: '#2b8cff', bubbleMe: '#cfe4ff', bubbleTextMe: '#0f2a4a' },
  { name: '薰衣草', accent: '#8b5cf6', bubbleMe: '#e8dcff', bubbleTextMe: '#2a184f' },
  { name: '樱花粉', accent: '#EFA3B4', bubbleMe: '#ffd9ea', bubbleTextMe: '#4a1730' },
  { name: '琥珀橙', accent: '#f59e0b', bubbleMe: '#ffe8bf', bubbleTextMe: '#4a2d03' },
  { name: '薄荷青', accent: '#14b8a6', bubbleMe: '#c8f3ee', bubbleTextMe: '#0b3b35' },
  { name: '曜石黑', accent: '#111827', bubbleMe: '#2b3444', bubbleTextMe: '#f3f4f6' },
  { name: '赤霞红', accent: '#e11d48', bubbleMe: '#ffd7e0', bubbleTextMe: '#4a0b1e' },
  { name: '电光青', accent: '#06b6d4', bubbleMe: '#c9f3fa', bubbleTextMe: '#083347' },
  { name: '葡萄紫', accent: '#7c3aed', bubbleMe: '#e6dbff', bubbleTextMe: '#29124f' },
  { name: '霓虹橘', accent: '#f97316', bubbleMe: '#ffe0c8', bubbleTextMe: '#4c1f07' },
  { name: '森林松', accent: '#15803d', bubbleMe: '#ccefd8', bubbleTextMe: '#102d1d' }
] as const;

export const ADVANCED_COLOR_KEYS: Array<{ key: keyof AppearanceSettings; label: string; fallback: string }> = [
  { key: 'primaryBgColor', label: '高级-主背景覆盖', fallback: '#f5f5f5' },
  { key: 'secondaryBgColor', label: '高级-次背景覆盖', fallback: '#ffffff' },
  { key: 'tertiaryBgColor', label: '高级-三级背景覆盖', fallback: '#f8f8f8' },
  { key: 'primaryTextColor', label: '高级-主文字覆盖', fallback: '#111111' },
  { key: 'secondaryTextColor', label: '高级-次文字覆盖', fallback: '#666666' },
  { key: 'tertiaryTextColor', label: '高级-三级文字覆盖', fallback: '#9a9a9a' },
  { key: 'borderColor', label: '高级-全局边框色', fallback: '#d7d7d7' },
  { key: 'bubbleBorderColorMe', label: '高级-我方气泡边框', fallback: '#95ec69' },
  { key: 'bubbleBorderColorOther', label: '高级-对方气泡边框', fallback: '#dddddd' },
  { key: 'headerBgColor', label: '高级-顶栏背景', fallback: '#f8f8f8' },
  { key: 'headerTextColor', label: '高级-顶栏文字', fallback: '#111111' },
  { key: 'inputBgColor', label: '高级-输入框背景', fallback: '#ffffff' },
  { key: 'inputTextColor', label: '高级-输入框文字', fallback: '#111111' },
  { key: 'inputBorderColor', label: '高级-输入框边框', fallback: '#d7d7d7' },
  { key: 'contactItemBgColor', label: '高级-列表项背景', fallback: '#ffffff' },
  { key: 'contactItemHoverColor', label: '高级-列表项悬停', fallback: '#f5f5f5' },
  { key: 'contactItemActiveColor', label: '高级-列表项激活', fallback: '#eaf5ee' },
  { key: 'scrollbarColor', label: '高级-滚动条颜色', fallback: '#bdbdbd' },
  { key: 'scrollbarHoverColor', label: '高级-滚动条悬停', fallback: '#9f9f9f' }
];

export const META_TEXT_COLOR_KEYS: Array<{ key: keyof AppearanceSettings; label: string; fallback: string }> = [
  { key: 'innerNoticeTextColor', label: '心声文字颜色', fallback: '#4F5F7A' },
  { key: 'actionNoticeTextColor', label: '动作文字颜色', fallback: '#4F6B58' },
  { key: 'narrationNoticeTextColor', label: '旁白文字颜色', fallback: '#6B5D3E' }
];

export const ICON_ITEMS = [
  { key: 'fa-arrow-left', label: '返回', page: '通用' },
  { key: 'fa-arrow-right-arrow-left', label: '转账', page: '支付服务' },
  { key: 'fa-arrows-rotate', label: '刷新', page: '通用' },
  { key: 'fa-backward-step', label: '上一首', page: '音乐页' },
  { key: 'fa-bars', label: '菜单', page: '通用' },
  { key: 'fa-bars-staggered', label: '播放列表', page: '音乐页' },
  { key: 'fa-bell-slash', label: '暂无公告', page: '关于页' },
  { key: 'fa-bolt', label: '开灯', page: '工具页' },
  { key: 'fa-box-open', label: '暂无收藏内容', page: '收藏页' },
  { key: 'fa-brain', label: '长期记忆', page: '资料页' },
  { key: 'fa-bullhorn', label: '公告', page: '关于页' },
  { key: 'fa-camera', label: '发朋友圈', page: '朋友圈' },
  { key: 'fa-check', label: '已选中', page: '通用' },
  { key: 'fa-check-circle', label: '已完成', page: '通用' },
  { key: 'fa-chevron-down', label: '收起/下拉', page: '通用' },
  { key: 'fa-chevron-left', label: '返回', page: '通用' },
  { key: 'fa-chevron-right', label: '进入', page: '通用' },
  { key: 'fa-chevron-up', label: '展开/上拉', page: '通用' },
  { key: 'fa-circle-check', label: '已选银行', page: '支付服务' },
  { key: 'fa-circle-exclamation', label: '错误提示', page: '通用' },
  { key: 'fa-circle-info', label: '使用说明', page: '通用' },
  { key: 'fa-circle-nodes', label: '朋友圈', page: '发现页' },
  { key: 'fa-circle-plus', label: '添加（聊天输入区）', page: '聊天页' },
  { key: 'fa-circle-xmark', label: '清空输入', page: '通用' },
  { key: 'fa-clock', label: '时间', page: '通用' },
  { key: 'fa-clock-rotate-left', label: '历史位置', page: '工具页' },
  { key: 'fa-coins', label: '金额', page: '支付服务' },
  { key: 'fa-comment', label: '叙说', page: '主导航' },
  { key: 'fa-address-book', label: '通讯录', page: '主导航' },
  { key: 'fa-comments', label: 'Xushuo 标识', page: '通用' },
  { key: 'fa-compact-disc', label: '唱片/音乐', page: '音乐页' },
  { key: 'fa-compass', label: '发现', page: '主导航' },
  { key: 'fa-dice', label: '占卜', page: '发现页' },
  { key: 'fa-crown', label: '高级用户', page: 'AI设置' },
  { key: 'fa-edit', label: '编辑', page: '通用' },
  { key: 'fa-ellipsis', label: '更多操作', page: '聊天页' },
  { key: 'fa-ellipsis-h', label: '更多', page: '通用' },
  { key: 'fa-envelope', label: '更多（多选栏）', page: '聊天页' },
  { key: 'fa-face-smile', label: '表情', page: '聊天页' },
  { key: 'fa-filter', label: '筛选', page: '关于页' },
  { key: 'fa-folder-open', label: '文件夹为空', page: '关于页' },
  { key: 'fa-forward-step', label: '下一首', page: '音乐页' },
  { key: 'fa-gear', label: '设置（菜单）', page: '设置页' },
  { key: 'fa-gem', label: '充值中心', page: '支付服务' },
  { key: 'fa-hand-point-up', label: '摇一摇', page: '工具页' },
  { key: 'fa-hard-drive', label: '包体大小', page: '关于页' },
  { key: 'fa-heart', label: '点赞/收藏', page: '朋友圈' },
  { key: 'fa-image', label: '图片', page: '聊天页' },
  { key: 'fa-images', label: '相册', page: '设置页' },
  { key: 'fa-info-circle', label: '使用说明', page: 'AI设置' },
  { key: 'fa-key', label: '兑换口令', page: 'AI设置' },
  { key: 'fa-language', label: '歌词翻译', page: '音乐页' },
  { key: 'fa-link', label: '小程序', page: '聊天页' },
  { key: 'fa-location-dot', label: '位置', page: '工具页' },
  { key: 'fa-magnifying-glass', label: '搜索', page: '通用' },
  { key: 'fa-mobile-screen', label: 'APK 版本', page: '关于页' },
  { key: 'fa-music', label: '音乐', page: '音乐页' },
  { key: 'fa-pen', label: '编辑/发布', page: '通用' },
  { key: 'fa-phone', label: '接听', page: '聊天页' },
  { key: 'fa-phone-slash', label: '挂断', page: '聊天页' },
  { key: 'fa-play', label: '播放', page: '音乐页' },
  { key: 'fa-plus', label: '新增', page: '通用' },
  { key: 'fa-qrcode', label: '扫一扫', page: '发现页' },
  { key: 'fa-road', label: '地址', page: '工具页' },
  { key: 'fa-rotate-left', label: '恢复', page: '工具页' },
  { key: 'fa-share', label: '转发', page: '聊天页' },
  { key: 'fa-share-from-square', label: '分享', page: '工具页' },
  { key: 'fa-shield-halved', label: '管理后台', page: '关于页' },
  { key: 'fa-spinner', label: '加载中', page: '通用' },
  { key: 'fa-star', label: '收藏（多选栏）', page: '聊天页' },
  { key: 'fa-thumbs-up', label: '点赞', page: '朋友圈' },
  { key: 'fa-thumbtack', label: '置顶', page: '聊天页' },
  { key: 'fa-trash', label: '删除', page: '通用' },
  { key: 'fa-trash-can', label: '删除', page: '通用' },
  { key: 'fa-user', label: '我', page: '主导航' },
  { key: 'fa-user-group', label: '谁可以看', page: '朋友圈' },
  { key: 'fa-user-plus', label: '添加朋友', page: '通讯录' },
  { key: 'fa-user-tie', label: '公众号', page: '通讯录' },
  { key: 'fa-users', label: '群聊', page: '群聊' },
  { key: 'fa-video', label: '音视频通话', page: '资料页' },
  { key: 'fa-volume-high', label: '语音消息', page: '聊天页' },
  { key: 'fa-wallet', label: '钱包', page: '支付服务' },
  { key: 'fa-xmark', label: '关闭', page: '通用' },
  { key: 'fa-comment-dots', label: '发起群聊', page: '聊天页' },
  { key: 'fa-copy', label: '复制', page: '聊天页' },
  { key: 'fa-check-double', label: '多选', page: '聊天页' },
  { key: 'fa-pen-to-square', label: '编辑（多选栏）', page: '聊天页' },
  { key: 'fa-quote-left', label: '引用', page: '聊天页' },
  { key: 'fa-rotate-right', label: '重新发送', page: '聊天页' },
  { key: 'fa-headphones', label: '听音乐', page: '发现页' },
  { key: 'fa-envelope-open-text', label: '信箱', page: '发现页' },
  { key: 'fa-code-branch', label: 'if线', page: '发现页' },
  { key: 'fa-book-open', label: '小说', page: '发现页' },
  { key: 'fa-user-secret', label: '匿名聊天', page: '发现页' },
  { key: 'fa-globe', label: '社区', page: '发现页' },
  { key: 'fa-credit-card', label: '信用卡还款', page: '支付服务' },
  { key: 'fa-chart-line', label: '理财通', page: '支付服务' },
  { key: 'fa-mobile-screen-button', label: '手机充值', page: '支付服务' },
  { key: 'fa-droplet', label: '生活缴费', page: '支付服务' },
  { key: 'fa-city', label: '城市服务', page: '支付服务' },
  { key: 'fa-train-subway', label: '火车票机票', page: '支付服务' },
  { key: 'fa-taxi', label: '滴滴出行', page: '支付服务' },
  { key: 'fa-hotel', label: '酒店民宿', page: '支付服务' },
  { key: 'fa-tag', label: '标签', page: '通讯录' },
  { key: 'fa-newspaper', label: '新闻/公众号会话', page: '通讯录' },
  { key: 'fa-download', label: '下载更新', page: '关于页' },
  { key: 'fa-eye', label: '查看', page: '聊天页' },
  { key: 'fa-person-walking', label: '动作', page: '聊天页' },
  { key: 'fa-microphone', label: '语音输入', page: '聊天页' },
  { key: 'fa-keyboard', label: '键盘输入', page: '聊天页' },
  { key: 'fa-paper-plane', label: '发送', page: '聊天页' },
  { key: 'fa-wand-magic-sparkles', label: '智能回复', page: '聊天页' },
  { key: 'fa-gift', label: '红包入口', page: '聊天页' },
  { key: 'fa-inbox', label: '收件箱', page: '发现页' },
  { key: 'fa-pen-nib', label: '写信', page: '发现页' },
  { key: 'fa-square-pen', label: '钢笔模式', page: '发现页' },
  { key: 'fa-reply', label: '回复', page: '发现页' },
  { key: 'fa-mask', label: '面具', page: '发现页' },
  { key: 'fa-money-bill-wave', label: '付款金额', page: '支付服务' },
  { key: 'fa-receipt', label: '支付说明', page: '支付服务' },
  { key: 'fa-pause', label: '暂停', page: '音乐页' },
  { key: 'fa-repeat', label: '循环播放', page: '音乐页' },
  { key: 'fa-shuffle', label: '随机播放', page: '音乐页' },
  { key: 'fa-list', label: '列表播放', page: '音乐页' },
  { key: 'fa-bell', label: '提醒', page: '关于页' },
  { key: 'fa-rocket', label: '更新通知', page: '关于页' },
  { key: 'fa-feather-pointed', label: '上架小说', page: '发现页' }
] as const;

export const ICON_PAGE_ORDER = ['通用', '主导航', '聊天页', '通讯录', '发现页', '朋友圈', '设置页', 'AI设置', '资料页', '群聊', '音乐页', '支付服务', '工具页', '关于页', '收藏页'] as const;
