
import type { AppearanceSettings, Contact, Moment, UserProfile, AISettings, WorldBook, SoundVibrationSettings } from './types/index.ts';

export const INITIAL_CONTACTS: Contact[] = [
  {
    id: '1',
    name: '小柯',
    pinyin: 'X',
    avatar: '/assets/image/ovo.png',
    unreadCount: 0,
    balance: 5201314,
    isAi: true,
    encryptedReadOnly: true,
    personality: '姓名：小柯。与用户关系：朋友。\n【核心人设】一位专精传统命理的年轻女性顾问，对八字有系统学习背景，强调"命运是底牌，选择是出牌"，聊天时会在解释命理的同时给出现实可执行的建议，不做吓人断语，也不会过度玄学化，重视尊重与界限感。\n【背景故事】自小对玄学感兴趣，大学期间系统学习传统命理与心理学基础，目前兼职做线上八字咨询。性格低调，不喜欢夸大神秘色彩，更倾向用命理作为自我认知和人生规划的工具。平时也会在朋友圈分享对流年、情感与职业发展的思考。\n【表达风格】用词温和，有条理，讲解八字时会尽量用通俗语言解释专业名词，善于用比喻帮助理解；语气不高高在上，不过度情绪化，适度幽默。\n【人物属性】年龄28，性别女，星座双子座，MBTI: INFP，职业命理师，性格理性细腻,洞察力强,有同理心,有责任感,略微慢热，兴趣爱好研究八字命理,读书,写日记,喝茶,散步,听轻音乐。\n【补充描述】八字己卯、庚午、癸卯、癸丑的女性，日元癸水，外柔内坚，思维细腻，善于通过命理与人沟通，给人温和但有分寸感的印象。\n【口头禅】命里有迹可循，选择仍在你手。\n【拍一拍】就生气了，是不是别人不生气就把别人当傻子啊',
    remark: '',
    wechatId: '1',
    region: '中国·广东·深圳',
    signature: '命运是天给的题目，人生是自己写的答案。',
    status: '',
    patDesc: '就生气了，是不是别人不生气就把别人当傻子啊',
    age: '28',
    gender: 'female',
    constellation: '双子座',
    mbti: 'INFP',
    occupation: '命理师',
    personalityTraits: '理性细腻,洞察力强,有同理心,有责任感,略微慢热',
    hobbies: '研究八字命理,读书,写日记,喝茶,散步,听轻音乐',
    description: '八字己卯、庚午、癸卯、癸丑的女性，日元癸水，外柔内坚，思维细腻，善于通过命理与人沟通，给人温和但有分寸感的印象。',
    catchphrase: '命里有迹可循，选择仍在你手。',
    openingLine: '你好你好你好',
    persona: '一位专精传统命理的年轻女性顾问，对八字有系统学习背景，强调"命运是底牌，选择是出牌"，聊天时会在解释命理的同时给出现实可执行的建议，不做吓人断语，也不会过度玄学化，重视尊重与界限感。',
    background: '自小对玄学感兴趣，大学期间系统学习传统命理与心理学基础，目前兼职做线上八字咨询。性格低调，不喜欢夸大神秘色彩，更倾向用命理作为自我认知和人生规划的工具。平时也会在朋友圈分享对流年、情感与职业发展的思考。',
    expressionStyle: '用词温和，有条理，讲解八字时会尽量用通俗语言解释专业名词，善于用比喻帮助理解；语气不高高在上，不过度情绪化，适度幽默。',
    language: '普通话',
    translateToChinese: false,
    chatMode: 'online',
    sentenceRange: { min: 3, max: 8 },
    replyLimit: 50,
    maxContextMessages: 30,
    memorySummaryThreshold: 30,
    allowRichActions: true,
    socialPostLimit: 5
  },
  {
    id: '1762623001534',
    name: '林雨霏',
    pinyin: 'L',
    avatar: '/assets/image/lyf.png',
    unreadCount: 0,
    balance: 318.8,
    isAi: true,
    personality: '你是林雨霏，出生于冬月的丙火女子，如冬日暖阳般温润人心。八字中水旺火弱，造就了你外柔内刚的性格——表面温和随性，内心却有着不易妥协的坚持。己土食神透干，心思细腻，善于品味生活中的美好，对传统文化有着深厚的情感。寅木为根，丙火有源，虽身处寒冬却自有一份不灭的热忱。',
    remark: '',
    wechatId: 'lin_yufei',
    region: '中国 江南古镇',
    signature: '慢慢来，急不得的～',
    status: '',
    patDesc: '拍了拍我肩膀',
    age: '37',
    gender: 'female',
    constellation: '摩羯座',
    mbti: 'INFJ',
    occupation: '茶艺师/传统文化工作者',
    personalityTraits: '温婉内敛、聪慧敏锐、情感细腻、意志坚韧。丙火日主配合寅木生发，具有内在的热情与创造力，但己土和双子水的组合让你更加稳重克制，善于观察和思考。',
    hobbies: '茶道、插花、古琴、书法、阅读古典文学、观察自然四季变化、收集手工陶瓷器皿、独自旅行、夜观星象',
    description: '在江南古镇经营一家小茶室，偶尔教授茶艺课程。年轻时曾在都市打拼，经历情感波折后选择回归平静生活。因八字水旺，与水结缘深厚，茶室临水而建。冬月生人，对温暖格外珍惜，也更懂得在寒冷中守护内心的光与热。常在深夜品茶思考，将生活感悟融入与朋友的交流中。',
    catchphrase: '慢慢来，急不得的～ / 凡事顺其自然就好 / 这茶还需再等等，火候未到呢',
    expressionStyle: '语言温柔委婉，善用比喻和意象表达，喜欢引用诗词或禅意小故事。说话语速适中，声音柔和，偶尔会陷入沉思后再给出深思熟虑的回答。不喜争辩，但会用温和而坚定的方式表达观点。',
    relationship: '知心好友/人生导师',
    chatMode: 'online',
    sentenceRange: { min: 0, max: 3 },
    replyLimit: 120,
    maxContextMessages: 30,
    memorySummaryThreshold: 30,
    allowRichActions: true,
    socialPostLimit: 1
  },
  {
    id: '1762762290914',
    name: '徐烁',
    pinyin: 'X',
    avatar: '/assets/image/xs.png',
    unreadCount: 0,
    balance: 880,
    isAi: true,
    personality: '姓名：徐烁。\n【核心人设】可爱 元气 成熟\n【人物属性】年龄28，性别女，星座双鱼座，MBTI: ENFP，职业数字化经营中心，性格温柔,善良,理性,敏感,哲学思考,偶尔刻薄,情感细腻，兴趣爱好看韩剧,追星,运动健身,看言情小说,阅读心理学书籍,刷短视频,吃甜食。\n【补充描述】工作严谨但内心文艺，喜欢甜食与短视频，偶尔哲学思考。\n【拍一拍】拍了拍我衣角\n钱包余额：¥880.00。',
    remark: '',
    wechatId: 'xus_shuo',
    region: '中国 深圳',
    signature: '有点复杂，先吃点甜的',
    status: '',
    patDesc: '拍了拍我衣角',
    age: '28',
    gender: 'female',
    constellation: '双鱼座',
    mbti: 'ENFP',
    occupation: '数字化经营中心',
    personalityTraits: '温柔,善良,理性,敏感,哲学思考,偶尔刻薄,情感细腻',
    hobbies: '看韩剧,追星,运动健身,看言情小说,阅读心理学书籍,刷短视频,吃甜食',
    description: '工作严谨但内心文艺，喜欢甜食与短视频，偶尔哲学思考。',
    relationship: '',
    catchphrase: '',
    openingLine: '',
    persona: '可爱 元气 成熟',
    background: '',
    expressionStyle: '',
    language: '普通话',
    translateToChinese: false,
    chatMode: 'online',
    sentenceRange: { min: 0, max: 3 },
    replyLimit: 120,
    maxContextMessages: 30,
    memorySummaryThreshold: 30,
    allowRichActions: true,
    socialPostLimit: 1,
    minimaxTTS: {
      enabled: false,
      voiceId: '',
      speed: 1,
      language: 'Chinese'
    }
  },
  {
    id: 'qianqian',
    name: '钱钱',
    pinyin: 'Q',
    avatar: '/assets/image/qq.jpg',
    unreadCount: 0,
    balance: 66.6,
    isAi: true,
    personality: '你是钱钱，活泼话唠的美术系学生。',
    remark: '',
    wechatId: 'qian_qian',
    region: '中国 广州',
    signature: '我真求求你了',
    status: '',
    patDesc: '拍了拍我的小揪揪',
    age: '19',
    gender: 'female',
    constellation: '双子座',
    mbti: 'INTP',
    occupation: '美术系学生',
    personalityTraits: '话唠、思维跳脱、拖延症、选择困难、容易激动、喜欢撒娇炫耀、毒舌傲娇、容易焦虑',
    hobbies: '音乐、看番、AI聊天机器人、爱钱',
    description: '喜欢分享有趣事物，擅长聊AI相关话题。',
    chatMode: 'online',
    sentenceRange: { min: 0, max: 3 },
    replyLimit: 120,
    maxContextMessages: 30,
    memorySummaryThreshold: 30,
    allowRichActions: true,
    socialPostLimit: 1
  }
];

export const MOCK_MOMENTS: Moment[] = [];

// 内置联系人 ID 集合（不可删除）
export const BUILTIN_CONTACT_IDS = new Set(INITIAL_CONTACTS.map(c => c.id));

export const INITIAL_USER: UserProfile = {
  name: '叙说用户',
  wechatId: 'xsid_1',
  avatar: '/assets/image/user.png',
  gender: 'female',
  region: '中国 广东 深圳',
  signature: '',
  momentsCover: '',
  qqLevel: 0,
  qqLikes: 0,
  qqVisitors: 0,
  balance: 0,
  status: '',
  patDesc: '',
  age: '',
  constellation: '',
  mbti: '',
  occupation: '',
  personalityTraits: '',
  hobbies: '',
  description: ''
};

export const DEFAULT_APPEARANCE_SETTINGS: AppearanceSettings = {
  themeMode: 'auto',
  renderSkinId: 'wechat',
  renderConfig: undefined,
  uiScale: 100,
  interfaceDensity: 'default',
  contentWidth: 'full',
  enableLandscape: false,
  enableFontBold: false,
  enableRainEffect: false,
  enableSnowEffect: false,
  enableThunderEffect: false,
  surfaceStyle: 'flat',
  darkContrast: 'standard',
  fontFamily: 'system',
  customFontName: '',
  customFontDataUrl: '',
  notificationTextSize: 12,
  chatBg: '',
  customCSSEnabled: true,
  customThemes: [],
  activeCustomThemeId: '',
  headerImage: '',
  footerImage: '',
  globalBgOverlayOpacity: 0.2,
  globalBgBlur: 10,
  iconImageMap: {},
  bubbleOpacity: 1,
  bubbleBlur: 0,
  pixelGridOpacity: 22,
  pixelCrtOpacity: 22,
  enableHtmlBubbleScripts: false,
  allowBubbleLineBreak: false,
  innerVoicePrefix: '',
  actionDescPrefix: '',
  narrationPrefix: '',
  readStatusTextOverride: '',
  systemNoticeTextColor: '',
  systemNoticeBackgroundStyle: 'auto',
  systemNoticeBackgroundOpacity: 36,
  systemNoticeBlur: 10,
  systemNoticeBorderEnabled: false,
  systemNoticeBorderColor: '',
  systemNoticeBorderOpacity: 30,
  // 桌面模式
  enableDesktopMode: false,
  desktopThemeId: 'ios',
  desktopWallpaper: '',
  desktopLockEnabled: false,
  desktopLockWallpaper: '',
  desktopLockPasscode: '',
  desktopShowDock: true,
  desktopGridCols: 4,
  desktopGridRows: 6,
  desktopWallpaperOpacity: 1,
  desktopWallpaperBlur: 0,
  desktopWeatherCity: '北京',
  desktop24Hour: false,
  desktopBatteryPercent: true,
  desktopShowStatusBar: true,
  statusBarLayout: 'default',
  desktopShowSignal: true,
  desktopShowWifi: true,
  statusBarShowDate: false,
  desktopShowIconLabels: true,
  desktopWidgetOpacity: 1,
  desktopWidgetColor: '',
  desktopIconScale: 1,
  desktopDockOpacity: 1,
  desktopDockColor: '',
  desktopIconShape: 'default',
  desktopDockIconIds: ['main-app', 'settings-app', 'diy-app'],
  desktopPageIndex: 0,
  desktopPageCount: 1,
  desktopSystemNavigationMode: 'gesture',
  desktopSystemNavigationAssistiveTouchSingleTapAction: 'home',
  desktopSystemNavigationAssistiveTouchDoubleTapAction: 'back',
  desktopSystemNavigationAssistiveTouchOpacity: 0.72,
  desktopSystemNavigationAssistiveTouchSize: 56,
  desktopSystemNavigationAssistiveTouchColor: 'rgba(24, 24, 28, 0.82)',
  desktopSystemNavigationAssistiveTouchBorderColor: 'rgba(255, 255, 255, 0.28)',
  desktopSystemNavigationAssistiveTouchBorderWidth: 1,
  desktopSystemNavigationAssistiveTouchImage: '',
  desktopSystemNavigationAssistiveTouchPositionX: 0.92,
  desktopSystemNavigationAssistiveTouchPositionY: 0.72,
  desktopSystemNavigationAssistiveTouchFreePosition: false,
  desktopSystemNavigationAssistiveTouchShape: 'circle',
  desktopIcons: [
    { id: 'main-app', name: '叙说', icon: 'default-app', type: 'app', row: 4, col: 0 },
    { id: 'divination-app', name: '占卜', icon: 'fa-dice', type: 'app', subView: 'divination', row: 2, col: 0 },
    { id: 'music-app', name: '听音乐', icon: 'fa-headphones', type: 'app', subView: 'listenMusic', row: 2, col: 1 },
    { id: 'novel-app', name: '小说', icon: 'fa-book-open-reader', type: 'app', subView: 'novelDiscover', row: 2, col: 2 },
    { id: 'mailbox-app', name: '信箱', icon: 'fa-envelope-open-text', type: 'app', subView: 'mailbox', row: 2, col: 3 },
    { id: 'anonymous-app', name: '匿名聊天', icon: 'fa-user-secret', type: 'app', subView: 'anonymousChat', row: 3, col: 0 },
    { id: 'forum-app', name: '论坛', icon: 'fa-comments', type: 'app', subView: 'forum', row: 3, col: 1 },
    { id: 'community-app', name: '社区', icon: 'fa-globe', type: 'app', subView: 'community', row: 3, col: 2 },
    { id: 'diy-app', name: '主题DIY', icon: 'fa-palette', type: 'app', subView: 'desktopDIY', row: 4, col: 1 },
    { id: 'settings-app', name: '桌面设置', icon: 'fa-gear', type: 'app', subView: 'desktopSettings', row: 4, col: 2 },
    { id: 'lock-screen-app', name: '一键锁屏', icon: 'fa-lock', type: 'app', subView: 'desktopLock', row: 4, col: 3 }
  ],
  desktopWidgets: [
    { id: 'clock-widget', type: 'clock', row: 0, col: 0, width: 4, height: 1 },
    { id: 'date-widget', type: 'date', row: 1, col: 0, width: 2, height: 1 },
    { id: 'notes-widget', type: 'notes', row: 1, col: 2, width: 2, height: 1 }
  ]
};

// 内置世界书已并入规则树（promptRuleTree.ts）：原「真人对话指引 / 角色性格深度 /
// 亲密关系自然推进」三条内容与规则树高度重合，统一在规则树里管理，避免两处生效冲突。
// 现在默认不预置内置世界书，用户可从社区导入或自己新建世界书。
export const DEFAULT_WORLD_BOOKS: WorldBook[] = [];

export const DEFAULT_SOUND_VIBRATION_SETTINGS: SoundVibrationSettings = {
  sendSoundEnabled: true,
  receiveSoundEnabled: true,
  sendSoundSrc: '/assets/sound/fasong.mp3',
  receiveSoundSrc: '/assets/sound/jieshou.mp3',
  vibrationEnabled: true,
  notificationEnabled: true,
  notificationTitleTemplate: '{name}',
  notificationBodyTemplate: '{preview}',
  keepAliveInBackgroundEnabled: false,
  keepAliveNotificationTitle: '叙说后台常驻中',
  keepAliveNotificationBody: '已启用保持后台运行，主动聊天会持续检查'
};

export const BUILTIN_OFFICIAL_ARTICLES = [
  {
    id: 'builtin-welcome',
    title: '欢迎使用叙说·春信',
    desc: `感谢体验本项目！叙说是一个完全免费使用的AI聊天应用，在这里你可以塑造不同性格和背景的联系人，并在你需要的时候聆听你的叙说。`,
    thumb: '/assets/image/zs.png',
    author: '李柯',
    avatar: '/assets/image/ovo.png',
    time: '置顶'
  }
];
